name: Auto Commit Changes

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --local user.name "jesusdaver86"
          git config --local user.email "jesus.rivero86@gmail.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated commit" || echo "No changes to commit"
          git push
