name: Unzip and Commit Files

on:
  push:
    paths:
      - '*.zip'

jobs:
  unzip-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permiso esencial para hacer push
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Necesario para operaciones git posteriores

      - name: Unzip files
        run: |
          # Busca y descomprime todos los ZIPs
          for zipfile in *.zip; do
            unzip "$zipfile" -d .
            rm -f "$zipfile"
          done

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token automático
        run: |
          # Configuración de Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Asegura que estamos en la rama correcta
          git checkout ${{ github.ref_name }}
          
          # Añade, commitea y pushea los cambios
          git add .
          git status
          git commit -m "Auto-commit: Archivos descomprimidos [skip ci]" || echo "No hay cambios para commitear"
          git push origin ${{ github.ref_name }}
