      - name: Process ZIP files
        if: env.has_zips == 'true'
        run: |
          MAIN_ZIP="${{ env.main_zip }}"
          BASE_NAME="${MAIN_ZIP%.*}"
          
          # Verifica si hay archivos divididos
          if ls ${BASE_NAME}.z?? 2>/dev/null; then
            echo "Detectados archivos ZIP divididos - combinando..."
            zip -s 0 "$MAIN_ZIP" --out "combined_$MAIN_ZIP"
            echo "Descomprimiendo combined_$MAIN_ZIP..."
            if unzip -v "combined_$MAIN_ZIP" -d .; then
              echo "Descompresión exitosa."
            else
              echo "Error al descomprimir combined_$MAIN_ZIP"
              exit 1
            fi
            rm -f "combined_$MAIN_ZIP" ${BASE_NAME}.z??
          else
            echo "Procesando ZIP normal..."
            echo "Descomprimiendo $MAIN_ZIP..."
            if unzip -v "$MAIN_ZIP" -d .; then
              echo "Descompresión exitosa."
            else
              echo "Error al descomprimir $MAIN_ZIP"
              exit 1
            fi
          fi
          
          # Limpieza final
          rm -f "$MAIN_ZIP"
